# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9433b50e7a7c555e5b52e6f39e111effaa78a8d06ed3f23910f256aa8644fa7fa99063253092386e46ecd5f463cd17bb83da84239243b9bcaf7e5383b7c3e8f2

test:
  secret_key_base: b7b5688db08bb8c656535c35135b39bcab0574e3c4fb512f9b907fb04740de8285218197194bc60dc5328b68a9e2f59a8edbf0099c18db5656c8d31d77c48b6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
